### PR TITLE
Add mac build.

### PR DESCRIPTION
**Pull request by tiagofrepereira2012**
https://github.com/bioidiap/bob.io.matlab/issues/2

### CODE REVIEW

**Comment by tiagofrepereira2012** [comment]
@conda-forge/core

I managed to fix the issue adding `-pthread` in the CFLAGS and `-lpthread` in LDFLAGS, but I don't understand why do I have to do this to make it work with conda.

Also, after building I had an issue when I tried to load the library and the issue was fixed exporting this variable
`DYLD_FALLBACK_LIBRARY_PATH=$PREFIX/lib`.
Why should I do that? Btw, I took this tip from here https://github.com/conda-forge/libmatio-feedstock/blob/master/recipe/build.sh#L13

Thanks

**Comment by 183amir** [comment]
@conda-forge/core @tiagofrepereira2012 means this error:

```
ERROR: Failure: ImportError (dlopen(/Users/tiagodefreitaspereira/Documents/buildOutProjects/bioidiap/bob.io.matlab/bob/io/matlab/_library.so, 2): Library not loaded: @rpath/libmatio.4.dylib
  Referenced from: /Users/tiagodefreitaspereira/Documents/buildOutProjects/bioidiap/bob.io.matlab/bob/io/matlab/_library.so
  Reason: image not found)
```

**Comment by 183amir** [comment]
LGTM. Thanks @tiagofrepereira2012.

**Comment by pelson** [comment]
Sorry nobody got back to you @tiagofrepereira2012. I have an answer to the question you ask - I presume it is a surprise to you to need the `-pthread` option for `bob.io.matlab`? Could it be that the python you normally compile with already has that in the `python-confg` flags?

```
$ python-config --cflags

-I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE
```

I have no pthread in there, but maybe you do when not compiling with conda?

**Pull request merged**
